- name: Run the equivalent of "apt-get update" as a separate step
  raw: apt-get update

- name: Install Python
  raw: apt install python -y

- name: Gather facts
  setup:

- name: Ensure common packages are installed
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - aptitude
    - bash-completion
    - htop
    - pv
    - time
