- name: Add repository key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present

- name: Install Java
  apt:
    name: openjdk-8-jre-headless
    state: present

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Make Elasticsearch start on boot
  service:
    name: elasticsearch
    enabled: yes

- name: Configure Java heap size
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: ^-Xms
      line: -Xms{{ ansible_memtotal_mb // 2 }}m
    - regexp: ^-Xmx
      line: -Xmx{{ ansible_memtotal_mb // 2 }}m
  notify: Restart Elasticsearch

- name: Configure Elasticsearch network host
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: ^#?(network\.host:)
    line: \1 {{ ansible_all_ipv4_addresses|max }}
    backrefs: yes
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch is running
  service:
    name: elasticsearch
    state: started

- name: Install Kibana
  apt:
    name: kibana
    state: present

- name: Make Kibana start on boot
  service:
    name: kibana
    enabled: yes

- name: Configure Kibana
  blockinfile:
    path: /etc/kibana/kibana.yml
    block: |
      server.host: {{ ansible_all_ipv4_addresses|max }}
      elasticsearch.url: http://{{ ansible_all_ipv4_addresses|max }}:9200
  notify: Restart Kibana

- name: Ensure Kibana is running
  service:
    name: kibana
    state: started
